### ISSUE TITLE
bibliophilee.herokuapp.com not loading!

### ISSUE THREAD

**Issue by khalby786** [adarsh-gupta101/goodbooks#1]
Hi, 

While reviewing your TinkerHub BFH entry, I noticed the live demo wasn't working. 

http://bibliophilee.herokuapp.com/

Don't worry, this is not the actual review of your project, I just wanted to let you know!

![image](https://user-images.githubusercontent.com/38468163/119507565-92268080-bd8c-11eb-9c1f-4565ff0e7628.png)

☮️

**Comment by adarsh-gupta101** [comment]
Hey .
I just cross checked it and it is working perfectly.
Can you please check it and let me know if the problem persisits

**Comment by ekuttan** [comment]
Working for me as well! 👍

**Comment by khalby786** [comment]
Seems to be working now!
